"""initial schema

Revision ID: 692e51d842c9
Revises: 
Create Date: 2026-09-18 19:52:51.881723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692e51d842c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('glass', sa.Text(), nullable=True),
    sa.Column('garnish', sa.Text(), nullable=True),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parse_status IN ('ok', 'partial', 'failed')", name='cocktails_parse_status_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('cocktail_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('unresolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ingredients_amount_check'),
    sa.CheckConstraint('position > 0', name='ingredients_position_check'),
    sa.ForeignKeyConstraint(['cocktail_id'], ['cocktails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cocktail_id', 'position', name='ingredients_cocktail_id_position_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('cocktails')
    # ### end Alembic commands ###
